version: '3'
services:
  api:
    build: .
    ports:
     - "8080:8080"
  prom:
    build: 
      context: .
      dockerfile: Dockerfile.prom
    volumes:
      - "./prometheus.yml:/var/prometheus/prometheus.yml"
    ports:
     - "9090:9090"
  grafana:
    image: grafana/grafana
    ports:
     - "3000:3000"
    environment:
    - GF_SERVER_ROOT_URL=http://grafana.server.name
    - GF_SECURITY_ADMIN_PASSWORD=secret